services:
  #Container per il frontend
  frontend:
    image: nginx
    container_name: frontend-nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/:/usr/share/nginx/html
  
  #Container per il database mysql
  mysql:    
    image: mysql  
    container_name: mysql-container
    ports:
      - 3306:3306   
    environment:  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bike    
    volumes:  
      - ./backend/sql-init/Bike_Type.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/sql-init/Production.sql:/docker-entrypoint-initdb.d/2.sql
      - ./backend/sql-init/Task_Cost.sql:/docker-entrypoint-initdb.d/3.sql
      - ./backend/sql-init/Time_Task.sql:/docker-entrypoint-initdb.d/4.sql

 #Container per il backend e api
  backend:
    image: python
    container_name: backend-fastapi
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app/
    command: >
      sh -c 'cd app &&
      pip install -r requirements.txt &&
      python api.py'
 

