services:  
  #Container per il database mysql
  mysql:    
    image: mysql  
    container_name: mysql-container
    ports:
      - 3306:3306   
    environment:  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bike    
    volumes:  
      - ./sql-init/Bike_Type.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql-init/Production.sql:/docker-entrypoint-initdb.d/2.sql
      - ./sql-init/Task_Cost.sql:/docker-entrypoint-initdb.d/3.sql
      - ./sql-init/Time_Task.sql:/docker-entrypoint-initdb.d/4.sql

 #Container per l'app CLI
  backend:
    image: python
    container_name: app-cli
    volumes:
      - ./:/app/
    command: >
      sh -c 'cd app &&
      pip install -r requirementsCli.txt &&
      python makeBikeCli.py'
 

